// <auto-generated />
using BASITWEBAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BASITWEBAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230825090143_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("BASITWEBAPI.Models.Room", b =>
                {
                    b.Property<int>("roomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("roomName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("roomId");

                    b.ToTable("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
